version: '3.1'

services:
  flask_scheduler_test:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask_scheduler_test
    volumes:
      - ./:/var/www
    # networks:
    #   scheduler-test:
    #     aliases:
    #       - flask-app

  nginx_scheduler_test:
    image: nginx:1.13
    container_name: nginx_scheduler_test
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5001:80
    # networks:
    #   - scheduler-test
    restart: always
    depends_on:
      - flask_scheduler_test

# networks:
#   scheduler-test:
#     name: scheduler_test_network